# Generated by Django 4.2.5 on 2023-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('sent_to', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMS Gateway URL', models.URLField(help_text='Eg. smsgateway.com/api/send_sms.cgi')),
                ('message_parameter', models.CharField(help_text='Enter url parameter for message', max_length=64)),
                ('receiver_parameter', models.CharField(help_text='Enter url parameter for receiver nos', max_length=64)),
                ('Static Parameters', models.JSONField(help_text='Enter static url parameters here (Eg. sender=django, username=django, password=1234 etc.)')),
                ('Use POST', models.BooleanField(default=False)),
            ],
        ),
    ]
